### ISSUE TITLE
Error when 'Run the multi-view optimization'

### ISSUE THREAD

**Issue by Vincentqyw** [mihaidusmanu/local-feature-refinement#2]
Hi Dusmanu, 

Thank you to open source this great work.
Currently, I try to optimize SFM reconstructed model using your work. I run your code as follows scripts:

``` bash
python3 utils/extract_features_sift.py --image_path ./experiments/scene1/images
python3 utils/create_starting_database.py --colmap_path colmap --dataset_path ./experiments/scene1
python3 utils/create_image_list_file.py --dataset_path ./experiments/scene1
python3 utils/create_exhaustive_matching_list.py --dataset_path ./experiments/scene1
python3 custom_demo.py --colmap_path colmap --dataset_name scene1 --dataset_path ./experiments/scene1 --method_name sift
```
some errors occured when runing **'multi-view-refinement/build/solve'** : 

``` bash
# graph nodes: 12383
# graph edges: 37500
# tracks: 8787
max track size: 20
Graph-cut time: 15ms
# components: 8724
max component size: 39
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1215 15:15:45.792618 18968 problem_impl.cc:311] Duplicate parameter blocks in a residual parameter are not allowed. Parameter block pointers: [ 0x2b2c260  0x2b2c260 ]
*** Check failure stack trace: ***
F1215 15:15:45.792618 18967 problem_impl.cc:311] Duplicate parameter blocks in a residual parameter are not allowed. Parameter block pointers: [ 0x2b2c5f0  0x2b2c5f0 ]F1215 15:15:45.792618 18972 problem_impl.cc:311] Duplicate parameter blocks in a residual parameter are not allowed. Parameter block pointers: [ 0x2b2c4e0  0x2b2c4e0 ]
*** Check failure stack trace: ***
Traceback (most recent call last):
  File "reconstruction-scripts/reconstruction_pipeline.py", line 91, in <module>
    main()
  File "reconstruction-scripts/reconstruction_pipeline.py", line 77, in main
    args.matches_file, args.solution_file
  File "/home/xxx/local-feature-refinement/reconstruction-scripts/colmap_utils.py", line 106, in import_features
    with open(solution_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/sift-a1_2-solution.pb'

```
I guess it caused by some wrong data feeding to ceres solver, but I don't know how to solve this error, really appreciate it if you can help me with this.

**Comment by mihaidusmanu** [comment]
Hello. I never run into this issue before. Could you provide me with the matching list `match-list.txt` as well as the protobuf containing the matches `sift-scene1-matches.pb`? I will try to take a look later this week.

**Comment by Vincentqyw** [comment]
Thanks for your prompt reply.
The data contains  `match-list.txt` and `sift-scene1-matches.pb`  had sent to your ETHZ email.

**Comment by mihaidusmanu** [comment]
Thanks for forwarding me the data. I just took a look and I might know what the issue is: it seems like your matching list contains pairs with the same image (e.g., `1500000335667382812.png 1500000335667382812.png`). This will cause self loops in the optimization which are not handled. One work-around is to simply make sure that your matching list doesn't contain this kind of pairs.

The "general" fix should be to add something along the lines:
```
if (image_name1 == image_name2) {
    continue;
}
```
on L447 of `multi-view-refinement/solve.cc`, but I don't have access to my work PC currently to test it out.

**Comment by Vincentqyw** [comment]
thanks for your prompt reply again, your solution works for me:)
